language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.1
# command to install dependencies
install:
  - pip install .
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r test_requirements.txt
# command to run tests
script: python folderless/tests/runtests.py
